//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticsFactory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string MSNV { get; set; }
        public int PAY { get; set; }
        public int NEBT { get; set; }
        public bool isDelete { get; set; }
        public int ProductPrice { get; set; }
        public int TimePrice { get; set; }
        public int Wage { get; set; }
        public int Cash { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
