//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticsFactory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOutput
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOutput()
        {
            this.PaymentOutputs = new HashSet<PaymentOutput>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MSKH { get; set; }
        public string MSXE { get; set; }
        public double TruckWeight { get; set; }
        public string ProductName { get; set; }
        public double ProductWeight { get; set; }
        public double ProductPrice { get; set; }
        public double TotalAmount { get; set; }
        public double Payed { get; set; }
        public double Own { get; set; }
        public bool Paid { get; set; }
        public double TotalWeight { get; set; }
        public bool isDelete { get; set; }
        public int sack { get; set; }
        public Nullable<int> TypeSack { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentOutput> PaymentOutputs { get; set; }
    }
}
